### ISSUE TITLE
input prompt not working for simple_form integration

### ISSUE THREAD

**Issue by tanraya** [brainspec/enumerize#196] opened 2015-07-06 11:31 UTC
Hi!

I have a following model:

```ruby
class Stage < ActiveRecord::Base
  extend Enumerize

  enumerize :state, in: {
    working: 0,
    under_construction: 1
  }
end
```

and I'm trying to add a prompt to the input this way:

```erb
<%= f.input :state, prompt: 'Pick a state' %>
```

but it is not working. How to make it possible?

**Comment by nashby** [comment] 2015-07-28 17:56
@tanraya hi! what version of simple_form (if it's simple_form) and enumerize are you using?

**Comment by tanraya** [comment] 2015-07-28 21:25
@nashby simple_form 3.1.0 and enumerize 0.11.0 on Rails 4.2.1.

**Comment by nashby** [comment] 2015-08-01 12:24
@tanraya that's strange. I just tested with a new app and it works for me.  Can you please provide a sample application that reproduces the error?

**Comment by nashby** [comment] 2015-08-01 12:27
Closing it for now since looks like it's not enumerize issue.

**Closed by nashby** 2015-08-01 12:27 UTC

**Comment by tanraya** [comment] 2015-08-01 12:36
Ok, I will try to reproduce it in new app.
