### ISSUE TITLE
*_changed? methods are broken in 2.1.0

### ISSUE THREAD

**Issue by kapso** [brainspec/enumerize#272] opened 2017-04-06 01:28 UTC
```ruby
u = User.first
u.state_enum
=> "active"
u.state_enum = "active"
u.save #  In after_save callback u.state_enum_changed? is `true`
```

**Comment by lest** [comment] 2017-04-06 06:28
Unfortunately, I didn't manage to reproduce the error with the latest `enumerize` version. Can you please push a test application reproducing the issue?

**Comment by tkawa** [comment] 2017-04-16 02:50
[This comment](https://github.com/brainspec/enumerize/pull/264#discussion_r111115580) I post is probably caused by the same issue.

I write a test that reproduces the issue. In short, it occurs when using postgresql instead of sqlite3. 
https://travis-ci.org/tkawa/enumerize/builds/222464891
diff: https://github.com/brainspec/enumerize/compare/master...tkawa:master
(I hope you take this diff in after the issue is solved. I'll make a pull request if you prefer.)

**Comment by lest** [comment] 2017-04-21 18:38
@tkawa thanks a lot for the diff!

The issue is fixed in the master branch.

**Closed by lest** 2017-04-21 18:38 UTC

**Comment by tkawa** [comment] 2017-04-22 04:12
Thank you so much! :smile:
